### ISSUE TITLE
Plugin crashes

### ISSUE THREAD

**Issue by JulioV** [denzilferreira/com.aware.plugin.openweather#5]
The plugin crashes every time is trying to query the logging frequency from the client: https://github.com/denzilferreira/com.aware.plugin.openweather/blob/master/openWeather/src/main/java/com/aware/plugin/openweather/Plugin.java#L162

```
2-07 18:44:33.155 18783-18783/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.aware.plugin.openweather, PID: 18783
                                                   java.lang.NumberFormatException: Invalid long: ""
                                                       at java.lang.Long.invalidLong(Long.java:124)
                                                       at java.lang.Long.parseLong(Long.java:345)
                                                       at java.lang.Long.parseLong(Long.java:321)
                                                       at com.aware.plugin.openweather.Plugin.onConnected(Plugin.java:162)
                                                       at com.google.android.gms.common.internal.zzm.zzq(Unknown Source)
                                                       at com.google.android.gms.internal.zzaal.zzo(Unknown Source)
                                                       at com.google.android.gms.internal.zzaaj.zzvE(Unknown Source)
                                                       at com.google.android.gms.internal.zzaaj.onConnected(Unknown Source)
                                                       at com.google.android.gms.internal.zzaan.onConnected(Unknown Source)
                                                       at com.google.android.gms.internal.zzzy.onConnected(Unknown Source)
                                                       at com.google.android.gms.common.internal.zzl$1.onConnected(Unknown Source)
                                                       at com.google.android.gms.common.internal.zzf$zzj.zzwZ(Unknown Source)
                                                       at com.google.android.gms.common.internal.zzf$zza.zzc(Unknown Source)
                                                       at com.google.android.gms.common.internal.zzf$zza.zzu(Unknown Source)
                                                       at com.google.android.gms.common.internal.zzf$zze.zzxa(Unknown Source)
                                                       at com.google.android.gms.common.internal.zzf$zzd.handleMessage(Unknown Source)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
```

**Comment by denzilferreira** [comment]
Fixed in development.
